### ISSUE TITLE
Fields support

### ISSUE THREAD

**Issue by cloudshooterhuman** [quanturium/bouquet#1]
Hola

First, nice to see an RxLogger that support RxJava2 😄 .
I don't know if the fields support is a roadmap target or not .. but I hope to have support for fields.

**Comment by cloudshooterhuman** [comment]
BTW I don't think if it make sense or not ❓

**Comment by quanturium** [comment]
Can you wrap up your field into a method and annotate it with @RxLogger?

**Comment by cloudshooterhuman** [comment]
yes, but I don't think it will be good option on big projects..

**Comment by quanturium** [comment]
I'm having trouble seeing that. If you store your observable in a class variable, you are most likely calling a method to initialize it. Why not add the @RxLogger annotation to that method?

**Comment by quanturium** [comment]
I'm closing this for now. If you think about a way to achieve what you want, re-open a ticket with details.
